language: php
php:
  - 5.6

addons:
  hosts:
    - test.casebox.org

before_script:
 - curl -sS https://getcomposer.org/installer | php
 - php composer.phar install --no-interaction

script:
 - mkdir -p build/logs
 - phpunit tests/Test.php
 - phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v

