sudo: false
language: php
php:
  - 5.6

services:
  - mysql

cache:
    directories:
        - $HOME/download-cache

addons:
  hosts:
    - test.casebox.org

before_install:
    - mkdir -p $HOME/download-cache
    - mkdir -p build/logs
    - mkdir -p logs
    - mkdir -p data/tmp/minify
    - mysql -u root -e "CREATE USER 'local'@'%' IDENTIFIED BY 'h0st'"
    - mysql -u root -e "CREATE USER 'local'@'localhost' IDENTIFIED BY 'h0st'"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'local'@'%'"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'local'@'localhost'"

install:
#   - curl -sS https://getcomposer.org/installer | php
   - composer install
#   - php composer.phar install --no-interaction
   - composer.phar install --no-interaction

before_script:
  # copy and install solr
   - export SOLR_VERSION="5.1.0"
   - bash tests/server/solr/solr5-install.sh
   # may take few seconds to start and may not be available when the script is executed
   - sleep 3
  # add solr core cbtest_log
   - export SOLR_CORENAME="cbtest_log"
   - export SOLR_CONFIGSET="log"
   - bash tests/server/solr/solr5-addcore.sh
  # add solr core test
   - export SOLR_CORENAME="cbtest_test"
   - export SOLR_CONFIGSET="default"
   - bash tests/server/solr/solr5-addcore.sh
  # add php extensions
   - phpenv config-rm tests/server/php/myconfig.ini
  # autoinstall CASEBOX
   - php tests/auto_install.php

script:
 - phpunit -c tests/phpunit-travis.xml httpsdocs/classes/UnitTest/Tests/

after_script:
 - if [ -f vendor/bin/coveralls ] ; then php vendor/bin/coveralls -v || true ; fi
 - bash tests/server/solr/solr5-stop.sh
