sudo: required
language: php
php:
  - 5.6

addons:
  hosts:
    - test.casebox.org

before_script:
 - curl -sS https://getcomposer.org/installer | php
 - php composer.phar install --no-interaction
 - mysql -u root -e "CREATE USER 'local'@'%' IDENTIFIED BY 'h0st'"
 - mysql -u root -e "CREATE USER 'local'@'localhost' IDENTIFIED BY 'h0st'"
 - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'local'@'%'"
 - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'local'@'localhost'"
 - curl -O http://archive.apache.org/dist/lucene/solr/5.3.0/solr-5.3.0.tgz
 - tar xzf solr-5.3.0.tgz solr-5.3.0/bin/install_solr_service.sh --strip-components=2
 - sudo sh ./install_solr_service.sh solr-5.3.0.tgz

script:
 - mkdir -p build/logs
 - sudo php vendor/bin/phpunit -c phpunit.xml httpsdocs/classes/UnitTest/Tests/

after_script:
 - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'

