sudo: false
language: php
php:
  - 7.0

services:
  - mysql

cache:
    directories:
        - $HOME/download-cache

addons:
  hosts:
    - dev.casebox.local

before_install:
    - mkdir -p $HOME/download-cache
    - mkdir -p build/logs
    - mkdir -p logs
    - mkdir -p data/tmp/minify
    - mysql -u root -e "CREATE USER 'test'@'%' IDENTIFIED BY 't3st'"
    - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 't3st'"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'test'@'%'"
    - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'test'@'localhost'"

install:
#   - pecl install mbstring
#   - pecl install curl
   - curl -sS https://getcomposer.org/installer | php
#   - php composer.phar install --no-interaction
   - php composer.phar install --no-interaction
#   - echo "See php extensions:"
#   - php -m


before_script:
  # copy and install solr
   - export SOLR_VERSION="5.5.0"
   - export SOLR_PORT="8983"
   - bash src/Tests/solr5.sh --install
   # may take few seconds to start and may not be available when the script is executed
   - sleep 3
  # add solr core cbtest_log
   - export SOLR_CORENAME="cb_log"
   - export SOLR_CONFIGSET="cb_log"
   - bash src/Tests/solr5.sh --addcore
  # add solr core test
   - export SOLR_CORENAME="cb_default"
   - export SOLR_CONFIGSET="/var/solr/default/conf"
   - bash src/Tests/solr5.sh --addcore
  # add php extensions
#   - phpenv config-add "${TRAVIS_BUILD_DIR}/tests/server/php/config-extensions.ini"
  # autoinstall CASEBOX
   - php tests/auto_install.php

script:
   - vendor/bin/phpunit -c src/Tests/phpunit.xml 

after_script:
 - if [ -f vendor/bin/coveralls ] ; then php vendor/bin/coveralls -v || true ; fi
 - bash src/Tests/solr5.sh --stop
